// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  TypedMap,
  Entity,
  Value,
  ValueKind,
  store,
  Bytes,
  BigInt,
  BigDecimal
} from "@graphprotocol/graph-ts";

export class ChallengeInfoUpdated extends Entity {
  constructor(id: Bytes) {
    super();
    this.set("id", Value.fromBytes(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save ChallengeInfoUpdated entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.BYTES,
        `Entities of type ChallengeInfoUpdated must have an ID of type Bytes but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("ChallengeInfoUpdated", id.toBytes().toHexString(), this);
    }
  }

  static loadInBlock(id: Bytes): ChallengeInfoUpdated | null {
    return changetype<ChallengeInfoUpdated | null>(
      store.get_in_block("ChallengeInfoUpdated", id.toHexString())
    );
  }

  static load(id: Bytes): ChallengeInfoUpdated | null {
    return changetype<ChallengeInfoUpdated | null>(
      store.get("ChallengeInfoUpdated", id.toHexString())
    );
  }

  get id(): Bytes {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set id(value: Bytes) {
    this.set("id", Value.fromBytes(value));
  }

  get challengeId(): Bytes {
    let value = this.get("challengeId");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set challengeId(value: Bytes) {
    this.set("challengeId", Value.fromBytes(value));
  }

  get challengeInfo_sourceTxFrom(): BigInt {
    let value = this.get("challengeInfo_sourceTxFrom");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set challengeInfo_sourceTxFrom(value: BigInt) {
    this.set("challengeInfo_sourceTxFrom", Value.fromBigInt(value));
  }

  get challengeInfo_sourceTxTime(): BigInt {
    let value = this.get("challengeInfo_sourceTxTime");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set challengeInfo_sourceTxTime(value: BigInt) {
    this.set("challengeInfo_sourceTxTime", Value.fromBigInt(value));
  }

  get challengeInfo_challenger(): Bytes {
    let value = this.get("challengeInfo_challenger");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set challengeInfo_challenger(value: Bytes) {
    this.set("challengeInfo_challenger", Value.fromBytes(value));
  }

  get challengeInfo_freezeToken(): Bytes {
    let value = this.get("challengeInfo_freezeToken");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set challengeInfo_freezeToken(value: Bytes) {
    this.set("challengeInfo_freezeToken", Value.fromBytes(value));
  }

  get challengeInfo_challengeUserRatio(): BigInt {
    let value = this.get("challengeInfo_challengeUserRatio");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set challengeInfo_challengeUserRatio(value: BigInt) {
    this.set("challengeInfo_challengeUserRatio", Value.fromBigInt(value));
  }

  get challengeInfo_freezeAmount0(): BigInt {
    let value = this.get("challengeInfo_freezeAmount0");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set challengeInfo_freezeAmount0(value: BigInt) {
    this.set("challengeInfo_freezeAmount0", Value.fromBigInt(value));
  }

  get challengeInfo_freezeAmount1(): BigInt {
    let value = this.get("challengeInfo_freezeAmount1");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set challengeInfo_freezeAmount1(value: BigInt) {
    this.set("challengeInfo_freezeAmount1", Value.fromBigInt(value));
  }

  get challengeInfo_challengeTime(): BigInt {
    let value = this.get("challengeInfo_challengeTime");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set challengeInfo_challengeTime(value: BigInt) {
    this.set("challengeInfo_challengeTime", Value.fromBigInt(value));
  }

  get challengeInfo_abortTime(): BigInt {
    let value = this.get("challengeInfo_abortTime");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set challengeInfo_abortTime(value: BigInt) {
    this.set("challengeInfo_abortTime", Value.fromBigInt(value));
  }

  get challengeInfo_verifiedTime0(): BigInt {
    let value = this.get("challengeInfo_verifiedTime0");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set challengeInfo_verifiedTime0(value: BigInt) {
    this.set("challengeInfo_verifiedTime0", Value.fromBigInt(value));
  }

  get challengeInfo_verifiedTime1(): BigInt {
    let value = this.get("challengeInfo_verifiedTime1");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set challengeInfo_verifiedTime1(value: BigInt) {
    this.set("challengeInfo_verifiedTime1", Value.fromBigInt(value));
  }

  get challengeInfo_verifiedDataHash0(): Bytes {
    let value = this.get("challengeInfo_verifiedDataHash0");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set challengeInfo_verifiedDataHash0(value: Bytes) {
    this.set("challengeInfo_verifiedDataHash0", Value.fromBytes(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get blockTimestamp(): BigInt {
    let value = this.get("blockTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockTimestamp(value: BigInt) {
    this.set("blockTimestamp", Value.fromBigInt(value));
  }

  get transactionHash(): Bytes {
    let value = this.get("transactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set transactionHash(value: Bytes) {
    this.set("transactionHash", Value.fromBytes(value));
  }
}

export class ColumnArrayUpdated extends Entity {
  constructor(id: Bytes) {
    super();
    this.set("id", Value.fromBytes(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save ColumnArrayUpdated entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.BYTES,
        `Entities of type ColumnArrayUpdated must have an ID of type Bytes but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("ColumnArrayUpdated", id.toBytes().toHexString(), this);
    }
  }

  static loadInBlock(id: Bytes): ColumnArrayUpdated | null {
    return changetype<ColumnArrayUpdated | null>(
      store.get_in_block("ColumnArrayUpdated", id.toHexString())
    );
  }

  static load(id: Bytes): ColumnArrayUpdated | null {
    return changetype<ColumnArrayUpdated | null>(
      store.get("ColumnArrayUpdated", id.toHexString())
    );
  }

  get id(): Bytes {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set id(value: Bytes) {
    this.set("id", Value.fromBytes(value));
  }

  get impl(): Bytes {
    let value = this.get("impl");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set impl(value: Bytes) {
    this.set("impl", Value.fromBytes(value));
  }

  get columnArrayHash(): Bytes {
    let value = this.get("columnArrayHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set columnArrayHash(value: Bytes) {
    this.set("columnArrayHash", Value.fromBytes(value));
  }

  get dealers(): Array<Bytes> | null {
    let value = this.get("dealers");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBytesArray();
    }
  }

  set dealers(value: Array<Bytes> | null) {
    if (!value) {
      this.unset("dealers");
    } else {
      this.set("dealers", Value.fromBytesArray(<Array<Bytes>>value));
    }
  }

  get ebcs(): Array<Bytes> | null {
    let value = this.get("ebcs");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBytesArray();
    }
  }

  set ebcs(value: Array<Bytes> | null) {
    if (!value) {
      this.unset("ebcs");
    } else {
      this.set("ebcs", Value.fromBytesArray(<Array<Bytes>>value));
    }
  }

  get chainIds(): Array<BigInt> | null {
    let value = this.get("chainIds");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigIntArray();
    }
  }

  set chainIds(value: Array<BigInt> | null) {
    if (!value) {
      this.unset("chainIds");
    } else {
      this.set("chainIds", Value.fromBigIntArray(<Array<BigInt>>value));
    }
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get blockTimestamp(): BigInt {
    let value = this.get("blockTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockTimestamp(value: BigInt) {
    this.set("blockTimestamp", Value.fromBigInt(value));
  }

  get transactionHash(): Bytes {
    let value = this.get("transactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set transactionHash(value: Bytes) {
    this.set("transactionHash", Value.fromBytes(value));
  }
}

export class ResponseMakersUpdated extends Entity {
  constructor(id: Bytes) {
    super();
    this.set("id", Value.fromBytes(id));
  }

  save(): void {
    let id = this.get("id");
    assert(
      id != null,
      "Cannot save ResponseMakersUpdated entity without an ID"
    );
    if (id) {
      assert(
        id.kind == ValueKind.BYTES,
        `Entities of type ResponseMakersUpdated must have an ID of type Bytes but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("ResponseMakersUpdated", id.toBytes().toHexString(), this);
    }
  }

  static loadInBlock(id: Bytes): ResponseMakersUpdated | null {
    return changetype<ResponseMakersUpdated | null>(
      store.get_in_block("ResponseMakersUpdated", id.toHexString())
    );
  }

  static load(id: Bytes): ResponseMakersUpdated | null {
    return changetype<ResponseMakersUpdated | null>(
      store.get("ResponseMakersUpdated", id.toHexString())
    );
  }

  get id(): Bytes {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set id(value: Bytes) {
    this.set("id", Value.fromBytes(value));
  }

  get impl(): Bytes {
    let value = this.get("impl");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set impl(value: Bytes) {
    this.set("impl", Value.fromBytes(value));
  }

  get responseMakers(): Array<BigInt> | null {
    let value = this.get("responseMakers");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigIntArray();
    }
  }

  set responseMakers(value: Array<BigInt> | null) {
    if (!value) {
      this.unset("responseMakers");
    } else {
      this.set("responseMakers", Value.fromBigIntArray(<Array<BigInt>>value));
    }
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get blockTimestamp(): BigInt {
    let value = this.get("blockTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockTimestamp(value: BigInt) {
    this.set("blockTimestamp", Value.fromBigInt(value));
  }

  get transactionHash(): Bytes {
    let value = this.get("transactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set transactionHash(value: Bytes) {
    this.set("transactionHash", Value.fromBytes(value));
  }
}

export class RulesRootUpdated extends Entity {
  constructor(id: Bytes) {
    super();
    this.set("id", Value.fromBytes(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save RulesRootUpdated entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.BYTES,
        `Entities of type RulesRootUpdated must have an ID of type Bytes but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("RulesRootUpdated", id.toBytes().toHexString(), this);
    }
  }

  static loadInBlock(id: Bytes): RulesRootUpdated | null {
    return changetype<RulesRootUpdated | null>(
      store.get_in_block("RulesRootUpdated", id.toHexString())
    );
  }

  static load(id: Bytes): RulesRootUpdated | null {
    return changetype<RulesRootUpdated | null>(
      store.get("RulesRootUpdated", id.toHexString())
    );
  }

  get id(): Bytes {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set id(value: Bytes) {
    this.set("id", Value.fromBytes(value));
  }

  get impl(): Bytes {
    let value = this.get("impl");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set impl(value: Bytes) {
    this.set("impl", Value.fromBytes(value));
  }

  get ebc(): Bytes {
    let value = this.get("ebc");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set ebc(value: Bytes) {
    this.set("ebc", Value.fromBytes(value));
  }

  get rootWithVersion_root(): Bytes {
    let value = this.get("rootWithVersion_root");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set rootWithVersion_root(value: Bytes) {
    this.set("rootWithVersion_root", Value.fromBytes(value));
  }

  get rootWithVersion_version(): BigInt {
    let value = this.get("rootWithVersion_version");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set rootWithVersion_version(value: BigInt) {
    this.set("rootWithVersion_version", Value.fromBigInt(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get blockTimestamp(): BigInt {
    let value = this.get("blockTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockTimestamp(value: BigInt) {
    this.set("blockTimestamp", Value.fromBigInt(value));
  }

  get transactionHash(): Bytes {
    let value = this.get("transactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set transactionHash(value: Bytes) {
    this.set("transactionHash", Value.fromBytes(value));
  }

  get input(): Bytes {
    let value = this.get("input");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set input(value: Bytes) {
    this.set("input", Value.fromBytes(value));
  }
}

export class SpvUpdated extends Entity {
  constructor(id: Bytes) {
    super();
    this.set("id", Value.fromBytes(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save SpvUpdated entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.BYTES,
        `Entities of type SpvUpdated must have an ID of type Bytes but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("SpvUpdated", id.toBytes().toHexString(), this);
    }
  }

  static loadInBlock(id: Bytes): SpvUpdated | null {
    return changetype<SpvUpdated | null>(
      store.get_in_block("SpvUpdated", id.toHexString())
    );
  }

  static load(id: Bytes): SpvUpdated | null {
    return changetype<SpvUpdated | null>(
      store.get("SpvUpdated", id.toHexString())
    );
  }

  get id(): Bytes {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set id(value: Bytes) {
    this.set("id", Value.fromBytes(value));
  }

  get impl(): Bytes {
    let value = this.get("impl");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set impl(value: Bytes) {
    this.set("impl", Value.fromBytes(value));
  }

  get chainId(): BigInt {
    let value = this.get("chainId");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set chainId(value: BigInt) {
    this.set("chainId", Value.fromBigInt(value));
  }

  get spv(): Bytes {
    let value = this.get("spv");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set spv(value: Bytes) {
    this.set("spv", Value.fromBytes(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get blockTimestamp(): BigInt {
    let value = this.get("blockTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockTimestamp(value: BigInt) {
    this.set("blockTimestamp", Value.fromBigInt(value));
  }

  get transactionHash(): Bytes {
    let value = this.get("transactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set transactionHash(value: Bytes) {
    this.set("transactionHash", Value.fromBytes(value));
  }
}

export class MDCCreated extends Entity {
  constructor(id: Bytes) {
    super();
    this.set("id", Value.fromBytes(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save MDCCreated entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.BYTES,
        `Entities of type MDCCreated must have an ID of type Bytes but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("MDCCreated", id.toBytes().toHexString(), this);
    }
  }

  static loadInBlock(id: Bytes): MDCCreated | null {
    return changetype<MDCCreated | null>(
      store.get_in_block("MDCCreated", id.toHexString())
    );
  }

  static load(id: Bytes): MDCCreated | null {
    return changetype<MDCCreated | null>(
      store.get("MDCCreated", id.toHexString())
    );
  }

  get id(): Bytes {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set id(value: Bytes) {
    this.set("id", Value.fromBytes(value));
  }

  get maker(): Bytes {
    let value = this.get("maker");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set maker(value: Bytes) {
    this.set("maker", Value.fromBytes(value));
  }

  get mdc(): Bytes {
    let value = this.get("mdc");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set mdc(value: Bytes) {
    this.set("mdc", Value.fromBytes(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get blockTimestamp(): BigInt {
    let value = this.get("blockTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockTimestamp(value: BigInt) {
    this.set("blockTimestamp", Value.fromBigInt(value));
  }
}

export class MDC extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save MDC entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        `Entities of type MDC must have an ID of type String but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("MDC", id.toString(), this);
    }
  }

  static loadInBlock(id: string): MDC | null {
    return changetype<MDC | null>(store.get_in_block("MDC", id));
  }

  static load(id: string): MDC | null {
    return changetype<MDC | null>(store.get("MDC", id));
  }

  get id(): string {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toString();
    }
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get owner(): Bytes {
    let value = this.get("owner");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set owner(value: Bytes) {
    this.set("owner", Value.fromBytes(value));
  }

  get columnArrayHash(): Bytes | null {
    let value = this.get("columnArrayHash");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBytes();
    }
  }

  set columnArrayHash(value: Bytes | null) {
    if (!value) {
      this.unset("columnArrayHash");
    } else {
      this.set("columnArrayHash", Value.fromBytes(<Bytes>value));
    }
  }

  get responseMakers(): Array<Bytes> | null {
    let value = this.get("responseMakers");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBytesArray();
    }
  }

  set responseMakers(value: Array<Bytes> | null) {
    if (!value) {
      this.unset("responseMakers");
    } else {
      this.set("responseMakers", Value.fromBytesArray(<Array<Bytes>>value));
    }
  }

  get spvs(): Array<Bytes> | null {
    let value = this.get("spvs");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBytesArray();
    }
  }

  set spvs(value: Array<Bytes> | null) {
    if (!value) {
      this.unset("spvs");
    } else {
      this.set("spvs", Value.fromBytesArray(<Array<Bytes>>value));
    }
  }

  get chainIds(): Array<BigInt> | null {
    let value = this.get("chainIds");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigIntArray();
    }
  }

  set chainIds(value: Array<BigInt> | null) {
    if (!value) {
      this.unset("chainIds");
    } else {
      this.set("chainIds", Value.fromBigIntArray(<Array<BigInt>>value));
    }
  }

  get dealers(): Array<Bytes> | null {
    let value = this.get("dealers");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBytesArray();
    }
  }

  set dealers(value: Array<Bytes> | null) {
    if (!value) {
      this.unset("dealers");
    } else {
      this.set("dealers", Value.fromBytesArray(<Array<Bytes>>value));
    }
  }

  get bindEBC(): Array<string> {
    let value = this.get("bindEBC");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toStringArray();
    }
  }

  set bindEBC(value: Array<string>) {
    this.set("bindEBC", Value.fromStringArray(value));
  }

  get factory(): FactoryMangerLoader {
    return new FactoryMangerLoader(
      "MDC",
      this.get("id")!.toString(),
      "factory"
    );
  }

  get createblockNumber(): BigInt {
    let value = this.get("createblockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set createblockNumber(value: BigInt) {
    this.set("createblockNumber", Value.fromBigInt(value));
  }

  get createblockTimestamp(): BigInt {
    let value = this.get("createblockTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set createblockTimestamp(value: BigInt) {
    this.set("createblockTimestamp", Value.fromBigInt(value));
  }

  get createtransactionHash(): Bytes {
    let value = this.get("createtransactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set createtransactionHash(value: Bytes) {
    this.set("createtransactionHash", Value.fromBytes(value));
  }

  get lastestUpdatetransactionHash(): Bytes {
    let value = this.get("lastestUpdatetransactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set lastestUpdatetransactionHash(value: Bytes) {
    this.set("lastestUpdatetransactionHash", Value.fromBytes(value));
  }
}

export class FactoryManger extends Entity {
  constructor(id: Bytes) {
    super();
    this.set("id", Value.fromBytes(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save FactoryManger entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.BYTES,
        `Entities of type FactoryManger must have an ID of type Bytes but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("FactoryManger", id.toBytes().toHexString(), this);
    }
  }

  static loadInBlock(id: Bytes): FactoryManger | null {
    return changetype<FactoryManger | null>(
      store.get_in_block("FactoryManger", id.toHexString())
    );
  }

  static load(id: Bytes): FactoryManger | null {
    return changetype<FactoryManger | null>(
      store.get("FactoryManger", id.toHexString())
    );
  }

  get id(): Bytes {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set id(value: Bytes) {
    this.set("id", Value.fromBytes(value));
  }

  get mdcs(): Array<string> {
    let value = this.get("mdcs");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toStringArray();
    }
  }

  set mdcs(value: Array<string>) {
    this.set("mdcs", Value.fromStringArray(value));
  }

  get mdcCounts(): BigInt {
    let value = this.get("mdcCounts");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set mdcCounts(value: BigInt) {
    this.set("mdcCounts", Value.fromBigInt(value));
  }

  get lastestUpdateHash(): Bytes {
    let value = this.get("lastestUpdateHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set lastestUpdateHash(value: Bytes) {
    this.set("lastestUpdateHash", Value.fromBytes(value));
  }

  get lastestUpdateTimestamp(): BigInt {
    let value = this.get("lastestUpdateTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set lastestUpdateTimestamp(value: BigInt) {
    this.set("lastestUpdateTimestamp", Value.fromBigInt(value));
  }

  get lastestUpdateBlockNumber(): BigInt {
    let value = this.get("lastestUpdateBlockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set lastestUpdateBlockNumber(value: BigInt) {
    this.set("lastestUpdateBlockNumber", Value.fromBigInt(value));
  }
}

export class EBCManager extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save EBCManager entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        `Entities of type EBCManager must have an ID of type String but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("EBCManager", id.toString(), this);
    }
  }

  static loadInBlock(id: string): EBCManager | null {
    return changetype<EBCManager | null>(store.get_in_block("EBCManager", id));
  }

  static load(id: string): EBCManager | null {
    return changetype<EBCManager | null>(store.get("EBCManager", id));
  }

  get id(): string {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toString();
    }
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get ebcCounts(): BigInt {
    let value = this.get("ebcCounts");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set ebcCounts(value: BigInt) {
    this.set("ebcCounts", Value.fromBigInt(value));
  }

  get ebcs(): Array<string> {
    let value = this.get("ebcs");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toStringArray();
    }
  }

  set ebcs(value: Array<string>) {
    this.set("ebcs", Value.fromStringArray(value));
  }

  get lastestUpdateHash(): Bytes {
    let value = this.get("lastestUpdateHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set lastestUpdateHash(value: Bytes) {
    this.set("lastestUpdateHash", Value.fromBytes(value));
  }

  get lastestUpdateTimestamp(): BigInt {
    let value = this.get("lastestUpdateTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set lastestUpdateTimestamp(value: BigInt) {
    this.set("lastestUpdateTimestamp", Value.fromBigInt(value));
  }

  get lastestUpdateBlockNumber(): BigInt {
    let value = this.get("lastestUpdateBlockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set lastestUpdateBlockNumber(value: BigInt) {
    this.set("lastestUpdateBlockNumber", Value.fromBigInt(value));
  }
}

export class MDCBindEBC extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save MDCBindEBC entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        `Entities of type MDCBindEBC must have an ID of type String but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("MDCBindEBC", id.toString(), this);
    }
  }

  static loadInBlock(id: string): MDCBindEBC | null {
    return changetype<MDCBindEBC | null>(store.get_in_block("MDCBindEBC", id));
  }

  static load(id: string): MDCBindEBC | null {
    return changetype<MDCBindEBC | null>(store.get("MDCBindEBC", id));
  }

  get id(): string {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toString();
    }
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get rules(): Array<string> {
    let value = this.get("rules");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toStringArray();
    }
  }

  set rules(value: Array<string>) {
    this.set("rules", Value.fromStringArray(value));
  }

  get mdc(): MDCLoader {
    return new MDCLoader("MDCBindEBC", this.get("id")!.toString(), "mdc");
  }

  get lastestUpdateHash(): Bytes {
    let value = this.get("lastestUpdateHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set lastestUpdateHash(value: Bytes) {
    this.set("lastestUpdateHash", Value.fromBytes(value));
  }

  get lastestUpdateTimestamp(): BigInt {
    let value = this.get("lastestUpdateTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set lastestUpdateTimestamp(value: BigInt) {
    this.set("lastestUpdateTimestamp", Value.fromBigInt(value));
  }

  get lastestUpdateBlockNumber(): BigInt {
    let value = this.get("lastestUpdateBlockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set lastestUpdateBlockNumber(value: BigInt) {
    this.set("lastestUpdateBlockNumber", Value.fromBigInt(value));
  }
}

export class EBC extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save EBC entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        `Entities of type EBC must have an ID of type String but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("EBC", id.toString(), this);
    }
  }

  static loadInBlock(id: string): EBC | null {
    return changetype<EBC | null>(store.get_in_block("EBC", id));
  }

  static load(id: string): EBC | null {
    return changetype<EBC | null>(store.get("EBC", id));
  }

  get id(): string {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toString();
    }
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get mdcList(): Array<string> {
    let value = this.get("mdcList");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toStringArray();
    }
  }

  set mdcList(value: Array<string>) {
    this.set("mdcList", Value.fromStringArray(value));
  }

  get ebcManager(): EBCManagerLoader {
    return new EBCManagerLoader(
      "EBC",
      this.get("id")!.toString(),
      "ebcManager"
    );
  }

  get lastestUpdatetransactionHash(): Bytes {
    let value = this.get("lastestUpdatetransactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set lastestUpdatetransactionHash(value: Bytes) {
    this.set("lastestUpdatetransactionHash", Value.fromBytes(value));
  }
}

export class ruleTypes extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save ruleTypes entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        `Entities of type ruleTypes must have an ID of type String but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("ruleTypes", id.toString(), this);
    }
  }

  static loadInBlock(id: string): ruleTypes | null {
    return changetype<ruleTypes | null>(store.get_in_block("ruleTypes", id));
  }

  static load(id: string): ruleTypes | null {
    return changetype<ruleTypes | null>(store.get("ruleTypes", id));
  }

  get id(): string {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toString();
    }
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get chain0(): BigInt | null {
    let value = this.get("chain0");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set chain0(value: BigInt | null) {
    if (!value) {
      this.unset("chain0");
    } else {
      this.set("chain0", Value.fromBigInt(<BigInt>value));
    }
  }

  get chain1(): BigInt | null {
    let value = this.get("chain1");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set chain1(value: BigInt | null) {
    if (!value) {
      this.unset("chain1");
    } else {
      this.set("chain1", Value.fromBigInt(<BigInt>value));
    }
  }

  get chain0Status(): i32 {
    let value = this.get("chain0Status");
    if (!value || value.kind == ValueKind.NULL) {
      return 0;
    } else {
      return value.toI32();
    }
  }

  set chain0Status(value: i32) {
    this.set("chain0Status", Value.fromI32(value));
  }

  get chain1Status(): i32 {
    let value = this.get("chain1Status");
    if (!value || value.kind == ValueKind.NULL) {
      return 0;
    } else {
      return value.toI32();
    }
  }

  set chain1Status(value: i32) {
    this.set("chain1Status", Value.fromI32(value));
  }

  get chain0Token(): BigInt | null {
    let value = this.get("chain0Token");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set chain0Token(value: BigInt | null) {
    if (!value) {
      this.unset("chain0Token");
    } else {
      this.set("chain0Token", Value.fromBigInt(<BigInt>value));
    }
  }

  get chain1Token(): BigInt | null {
    let value = this.get("chain1Token");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set chain1Token(value: BigInt | null) {
    if (!value) {
      this.unset("chain1Token");
    } else {
      this.set("chain1Token", Value.fromBigInt(<BigInt>value));
    }
  }

  get chain0minPrice(): BigInt | null {
    let value = this.get("chain0minPrice");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set chain0minPrice(value: BigInt | null) {
    if (!value) {
      this.unset("chain0minPrice");
    } else {
      this.set("chain0minPrice", Value.fromBigInt(<BigInt>value));
    }
  }

  get chain1minPrice(): BigInt | null {
    let value = this.get("chain1minPrice");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set chain1minPrice(value: BigInt | null) {
    if (!value) {
      this.unset("chain1minPrice");
    } else {
      this.set("chain1minPrice", Value.fromBigInt(<BigInt>value));
    }
  }

  get chain0maxPrice(): BigInt | null {
    let value = this.get("chain0maxPrice");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set chain0maxPrice(value: BigInt | null) {
    if (!value) {
      this.unset("chain0maxPrice");
    } else {
      this.set("chain0maxPrice", Value.fromBigInt(<BigInt>value));
    }
  }

  get chain1maxPrice(): BigInt | null {
    let value = this.get("chain1maxPrice");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set chain1maxPrice(value: BigInt | null) {
    if (!value) {
      this.unset("chain1maxPrice");
    } else {
      this.set("chain1maxPrice", Value.fromBigInt(<BigInt>value));
    }
  }

  get chain0WithholdingFee(): BigInt | null {
    let value = this.get("chain0WithholdingFee");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set chain0WithholdingFee(value: BigInt | null) {
    if (!value) {
      this.unset("chain0WithholdingFee");
    } else {
      this.set("chain0WithholdingFee", Value.fromBigInt(<BigInt>value));
    }
  }

  get chain1WithholdingFee(): BigInt | null {
    let value = this.get("chain1WithholdingFee");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set chain1WithholdingFee(value: BigInt | null) {
    if (!value) {
      this.unset("chain1WithholdingFee");
    } else {
      this.set("chain1WithholdingFee", Value.fromBigInt(<BigInt>value));
    }
  }

  get chain0TradeFee(): i32 {
    let value = this.get("chain0TradeFee");
    if (!value || value.kind == ValueKind.NULL) {
      return 0;
    } else {
      return value.toI32();
    }
  }

  set chain0TradeFee(value: i32) {
    this.set("chain0TradeFee", Value.fromI32(value));
  }

  get chain1TradeFee(): i32 {
    let value = this.get("chain1TradeFee");
    if (!value || value.kind == ValueKind.NULL) {
      return 0;
    } else {
      return value.toI32();
    }
  }

  set chain1TradeFee(value: i32) {
    this.set("chain1TradeFee", Value.fromI32(value));
  }

  get chain0ResponseTime(): i32 {
    let value = this.get("chain0ResponseTime");
    if (!value || value.kind == ValueKind.NULL) {
      return 0;
    } else {
      return value.toI32();
    }
  }

  set chain0ResponseTime(value: i32) {
    this.set("chain0ResponseTime", Value.fromI32(value));
  }

  get chain1ResponseTime(): i32 {
    let value = this.get("chain1ResponseTime");
    if (!value || value.kind == ValueKind.NULL) {
      return 0;
    } else {
      return value.toI32();
    }
  }

  set chain1ResponseTime(value: i32) {
    this.set("chain1ResponseTime", Value.fromI32(value));
  }

  get chain0CompensationRatio(): i32 {
    let value = this.get("chain0CompensationRatio");
    if (!value || value.kind == ValueKind.NULL) {
      return 0;
    } else {
      return value.toI32();
    }
  }

  set chain0CompensationRatio(value: i32) {
    this.set("chain0CompensationRatio", Value.fromI32(value));
  }

  get chain1CompensationRatio(): i32 {
    let value = this.get("chain1CompensationRatio");
    if (!value || value.kind == ValueKind.NULL) {
      return 0;
    } else {
      return value.toI32();
    }
  }

  set chain1CompensationRatio(value: i32) {
    this.set("chain1CompensationRatio", Value.fromI32(value));
  }

  get mdcBindebc(): MDCBindEBCLoader {
    return new MDCBindEBCLoader(
      "ruleTypes",
      this.get("id")!.toString(),
      "mdcBindebc"
    );
  }

  get root(): Bytes {
    let value = this.get("root");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set root(value: Bytes) {
    this.set("root", Value.fromBytes(value));
  }

  get version(): i32 {
    let value = this.get("version");
    if (!value || value.kind == ValueKind.NULL) {
      return 0;
    } else {
      return value.toI32();
    }
  }

  set version(value: i32) {
    this.set("version", Value.fromI32(value));
  }
}

export class ChainInfoUpdated extends Entity {
  constructor(id: Bytes) {
    super();
    this.set("id", Value.fromBytes(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save ChainInfoUpdated entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.BYTES,
        `Entities of type ChainInfoUpdated must have an ID of type Bytes but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("ChainInfoUpdated", id.toBytes().toHexString(), this);
    }
  }

  static loadInBlock(id: Bytes): ChainInfoUpdated | null {
    return changetype<ChainInfoUpdated | null>(
      store.get_in_block("ChainInfoUpdated", id.toHexString())
    );
  }

  static load(id: Bytes): ChainInfoUpdated | null {
    return changetype<ChainInfoUpdated | null>(
      store.get("ChainInfoUpdated", id.toHexString())
    );
  }

  get id(): Bytes {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set id(value: Bytes) {
    this.set("id", Value.fromBytes(value));
  }

  get ORManager_id(): BigInt {
    let value = this.get("ORManager_id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set ORManager_id(value: BigInt) {
    this.set("ORManager_id", Value.fromBigInt(value));
  }

  get chainInfo_id(): BigInt {
    let value = this.get("chainInfo_id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set chainInfo_id(value: BigInt) {
    this.set("chainInfo_id", Value.fromBigInt(value));
  }

  get chainInfo_batchLimit(): BigInt {
    let value = this.get("chainInfo_batchLimit");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set chainInfo_batchLimit(value: BigInt) {
    this.set("chainInfo_batchLimit", Value.fromBigInt(value));
  }

  get chainInfo_minVerifyChallengeSourceTxSecond(): BigInt {
    let value = this.get("chainInfo_minVerifyChallengeSourceTxSecond");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set chainInfo_minVerifyChallengeSourceTxSecond(value: BigInt) {
    this.set(
      "chainInfo_minVerifyChallengeSourceTxSecond",
      Value.fromBigInt(value)
    );
  }

  get chainInfo_maxVerifyChallengeSourceTxSecond(): BigInt {
    let value = this.get("chainInfo_maxVerifyChallengeSourceTxSecond");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set chainInfo_maxVerifyChallengeSourceTxSecond(value: BigInt) {
    this.set(
      "chainInfo_maxVerifyChallengeSourceTxSecond",
      Value.fromBigInt(value)
    );
  }

  get chainInfo_minVerifyChallengeDestTxSecond(): BigInt {
    let value = this.get("chainInfo_minVerifyChallengeDestTxSecond");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set chainInfo_minVerifyChallengeDestTxSecond(value: BigInt) {
    this.set(
      "chainInfo_minVerifyChallengeDestTxSecond",
      Value.fromBigInt(value)
    );
  }

  get chainInfo_maxVerifyChallengeDestTxSecond(): BigInt {
    let value = this.get("chainInfo_maxVerifyChallengeDestTxSecond");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set chainInfo_maxVerifyChallengeDestTxSecond(value: BigInt) {
    this.set(
      "chainInfo_maxVerifyChallengeDestTxSecond",
      Value.fromBigInt(value)
    );
  }

  get chainInfo_spvs(): Array<Bytes> {
    let value = this.get("chainInfo_spvs");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytesArray();
    }
  }

  set chainInfo_spvs(value: Array<Bytes>) {
    this.set("chainInfo_spvs", Value.fromBytesArray(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get blockTimestamp(): BigInt {
    let value = this.get("blockTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockTimestamp(value: BigInt) {
    this.set("blockTimestamp", Value.fromBigInt(value));
  }

  get transactionHash(): Bytes {
    let value = this.get("transactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set transactionHash(value: Bytes) {
    this.set("transactionHash", Value.fromBytes(value));
  }
}

export class ChainTokenUpdated extends Entity {
  constructor(id: Bytes) {
    super();
    this.set("id", Value.fromBytes(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save ChainTokenUpdated entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.BYTES,
        `Entities of type ChainTokenUpdated must have an ID of type Bytes but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("ChainTokenUpdated", id.toBytes().toHexString(), this);
    }
  }

  static loadInBlock(id: Bytes): ChainTokenUpdated | null {
    return changetype<ChainTokenUpdated | null>(
      store.get_in_block("ChainTokenUpdated", id.toHexString())
    );
  }

  static load(id: Bytes): ChainTokenUpdated | null {
    return changetype<ChainTokenUpdated | null>(
      store.get("ChainTokenUpdated", id.toHexString())
    );
  }

  get id(): Bytes {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set id(value: Bytes) {
    this.set("id", Value.fromBytes(value));
  }

  get ORManager_id(): BigInt {
    let value = this.get("ORManager_id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set ORManager_id(value: BigInt) {
    this.set("ORManager_id", Value.fromBigInt(value));
  }

  get tokenInfo_token(): BigInt {
    let value = this.get("tokenInfo_token");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set tokenInfo_token(value: BigInt) {
    this.set("tokenInfo_token", Value.fromBigInt(value));
  }

  get tokenInfo_mainnetToken(): Bytes {
    let value = this.get("tokenInfo_mainnetToken");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set tokenInfo_mainnetToken(value: Bytes) {
    this.set("tokenInfo_mainnetToken", Value.fromBytes(value));
  }

  get tokenInfo_decimals(): i32 {
    let value = this.get("tokenInfo_decimals");
    if (!value || value.kind == ValueKind.NULL) {
      return 0;
    } else {
      return value.toI32();
    }
  }

  set tokenInfo_decimals(value: i32) {
    this.set("tokenInfo_decimals", Value.fromI32(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get blockTimestamp(): BigInt {
    let value = this.get("blockTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockTimestamp(value: BigInt) {
    this.set("blockTimestamp", Value.fromBigInt(value));
  }

  get transactionHash(): Bytes {
    let value = this.get("transactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set transactionHash(value: Bytes) {
    this.set("transactionHash", Value.fromBytes(value));
  }
}

export class ChallengeUserRatioUpdated extends Entity {
  constructor(id: Bytes) {
    super();
    this.set("id", Value.fromBytes(id));
  }

  save(): void {
    let id = this.get("id");
    assert(
      id != null,
      "Cannot save ChallengeUserRatioUpdated entity without an ID"
    );
    if (id) {
      assert(
        id.kind == ValueKind.BYTES,
        `Entities of type ChallengeUserRatioUpdated must have an ID of type Bytes but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("ChallengeUserRatioUpdated", id.toBytes().toHexString(), this);
    }
  }

  static loadInBlock(id: Bytes): ChallengeUserRatioUpdated | null {
    return changetype<ChallengeUserRatioUpdated | null>(
      store.get_in_block("ChallengeUserRatioUpdated", id.toHexString())
    );
  }

  static load(id: Bytes): ChallengeUserRatioUpdated | null {
    return changetype<ChallengeUserRatioUpdated | null>(
      store.get("ChallengeUserRatioUpdated", id.toHexString())
    );
  }

  get id(): Bytes {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set id(value: Bytes) {
    this.set("id", Value.fromBytes(value));
  }

  get challengeUserRatio(): BigInt {
    let value = this.get("challengeUserRatio");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set challengeUserRatio(value: BigInt) {
    this.set("challengeUserRatio", Value.fromBigInt(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get blockTimestamp(): BigInt {
    let value = this.get("blockTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockTimestamp(value: BigInt) {
    this.set("blockTimestamp", Value.fromBigInt(value));
  }

  get transactionHash(): Bytes {
    let value = this.get("transactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set transactionHash(value: Bytes) {
    this.set("transactionHash", Value.fromBytes(value));
  }
}

export class EbcsUpdated extends Entity {
  constructor(id: Bytes) {
    super();
    this.set("id", Value.fromBytes(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save EbcsUpdated entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.BYTES,
        `Entities of type EbcsUpdated must have an ID of type Bytes but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("EbcsUpdated", id.toBytes().toHexString(), this);
    }
  }

  static loadInBlock(id: Bytes): EbcsUpdated | null {
    return changetype<EbcsUpdated | null>(
      store.get_in_block("EbcsUpdated", id.toHexString())
    );
  }

  static load(id: Bytes): EbcsUpdated | null {
    return changetype<EbcsUpdated | null>(
      store.get("EbcsUpdated", id.toHexString())
    );
  }

  get id(): Bytes {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set id(value: Bytes) {
    this.set("id", Value.fromBytes(value));
  }

  get ebcs(): Array<Bytes> {
    let value = this.get("ebcs");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytesArray();
    }
  }

  set ebcs(value: Array<Bytes>) {
    this.set("ebcs", Value.fromBytesArray(value));
  }

  get statuses(): Array<boolean> {
    let value = this.get("statuses");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBooleanArray();
    }
  }

  set statuses(value: Array<boolean>) {
    this.set("statuses", Value.fromBooleanArray(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get blockTimestamp(): BigInt {
    let value = this.get("blockTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockTimestamp(value: BigInt) {
    this.set("blockTimestamp", Value.fromBigInt(value));
  }

  get transactionHash(): Bytes {
    let value = this.get("transactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set transactionHash(value: Bytes) {
    this.set("transactionHash", Value.fromBytes(value));
  }
}

export class FeeChallengeSecondUpdated extends Entity {
  constructor(id: Bytes) {
    super();
    this.set("id", Value.fromBytes(id));
  }

  save(): void {
    let id = this.get("id");
    assert(
      id != null,
      "Cannot save FeeChallengeSecondUpdated entity without an ID"
    );
    if (id) {
      assert(
        id.kind == ValueKind.BYTES,
        `Entities of type FeeChallengeSecondUpdated must have an ID of type Bytes but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("FeeChallengeSecondUpdated", id.toBytes().toHexString(), this);
    }
  }

  static loadInBlock(id: Bytes): FeeChallengeSecondUpdated | null {
    return changetype<FeeChallengeSecondUpdated | null>(
      store.get_in_block("FeeChallengeSecondUpdated", id.toHexString())
    );
  }

  static load(id: Bytes): FeeChallengeSecondUpdated | null {
    return changetype<FeeChallengeSecondUpdated | null>(
      store.get("FeeChallengeSecondUpdated", id.toHexString())
    );
  }

  get id(): Bytes {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set id(value: Bytes) {
    this.set("id", Value.fromBytes(value));
  }

  get feeChallengeSecond(): BigInt {
    let value = this.get("feeChallengeSecond");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set feeChallengeSecond(value: BigInt) {
    this.set("feeChallengeSecond", Value.fromBigInt(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get blockTimestamp(): BigInt {
    let value = this.get("blockTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockTimestamp(value: BigInt) {
    this.set("blockTimestamp", Value.fromBigInt(value));
  }

  get transactionHash(): Bytes {
    let value = this.get("transactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set transactionHash(value: Bytes) {
    this.set("transactionHash", Value.fromBytes(value));
  }
}

export class FeeTakeOnChallengeSecondUpdated extends Entity {
  constructor(id: Bytes) {
    super();
    this.set("id", Value.fromBytes(id));
  }

  save(): void {
    let id = this.get("id");
    assert(
      id != null,
      "Cannot save FeeTakeOnChallengeSecondUpdated entity without an ID"
    );
    if (id) {
      assert(
        id.kind == ValueKind.BYTES,
        `Entities of type FeeTakeOnChallengeSecondUpdated must have an ID of type Bytes but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set(
        "FeeTakeOnChallengeSecondUpdated",
        id.toBytes().toHexString(),
        this
      );
    }
  }

  static loadInBlock(id: Bytes): FeeTakeOnChallengeSecondUpdated | null {
    return changetype<FeeTakeOnChallengeSecondUpdated | null>(
      store.get_in_block("FeeTakeOnChallengeSecondUpdated", id.toHexString())
    );
  }

  static load(id: Bytes): FeeTakeOnChallengeSecondUpdated | null {
    return changetype<FeeTakeOnChallengeSecondUpdated | null>(
      store.get("FeeTakeOnChallengeSecondUpdated", id.toHexString())
    );
  }

  get id(): Bytes {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set id(value: Bytes) {
    this.set("id", Value.fromBytes(value));
  }

  get feeTakeOnChallengeSecond(): BigInt {
    let value = this.get("feeTakeOnChallengeSecond");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set feeTakeOnChallengeSecond(value: BigInt) {
    this.set("feeTakeOnChallengeSecond", Value.fromBigInt(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get blockTimestamp(): BigInt {
    let value = this.get("blockTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockTimestamp(value: BigInt) {
    this.set("blockTimestamp", Value.fromBigInt(value));
  }

  get transactionHash(): Bytes {
    let value = this.get("transactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set transactionHash(value: Bytes) {
    this.set("transactionHash", Value.fromBytes(value));
  }
}

export class MaxMDCLimitUpdated extends Entity {
  constructor(id: Bytes) {
    super();
    this.set("id", Value.fromBytes(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save MaxMDCLimitUpdated entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.BYTES,
        `Entities of type MaxMDCLimitUpdated must have an ID of type Bytes but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("MaxMDCLimitUpdated", id.toBytes().toHexString(), this);
    }
  }

  static loadInBlock(id: Bytes): MaxMDCLimitUpdated | null {
    return changetype<MaxMDCLimitUpdated | null>(
      store.get_in_block("MaxMDCLimitUpdated", id.toHexString())
    );
  }

  static load(id: Bytes): MaxMDCLimitUpdated | null {
    return changetype<MaxMDCLimitUpdated | null>(
      store.get("MaxMDCLimitUpdated", id.toHexString())
    );
  }

  get id(): Bytes {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set id(value: Bytes) {
    this.set("id", Value.fromBytes(value));
  }

  get maxMDCLimit(): BigInt {
    let value = this.get("maxMDCLimit");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set maxMDCLimit(value: BigInt) {
    this.set("maxMDCLimit", Value.fromBigInt(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get blockTimestamp(): BigInt {
    let value = this.get("blockTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockTimestamp(value: BigInt) {
    this.set("blockTimestamp", Value.fromBigInt(value));
  }

  get transactionHash(): Bytes {
    let value = this.get("transactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set transactionHash(value: Bytes) {
    this.set("transactionHash", Value.fromBytes(value));
  }
}

export class MinChallengeRatioUpdated extends Entity {
  constructor(id: Bytes) {
    super();
    this.set("id", Value.fromBytes(id));
  }

  save(): void {
    let id = this.get("id");
    assert(
      id != null,
      "Cannot save MinChallengeRatioUpdated entity without an ID"
    );
    if (id) {
      assert(
        id.kind == ValueKind.BYTES,
        `Entities of type MinChallengeRatioUpdated must have an ID of type Bytes but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("MinChallengeRatioUpdated", id.toBytes().toHexString(), this);
    }
  }

  static loadInBlock(id: Bytes): MinChallengeRatioUpdated | null {
    return changetype<MinChallengeRatioUpdated | null>(
      store.get_in_block("MinChallengeRatioUpdated", id.toHexString())
    );
  }

  static load(id: Bytes): MinChallengeRatioUpdated | null {
    return changetype<MinChallengeRatioUpdated | null>(
      store.get("MinChallengeRatioUpdated", id.toHexString())
    );
  }

  get id(): Bytes {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set id(value: Bytes) {
    this.set("id", Value.fromBytes(value));
  }

  get minChallengeRatio(): BigInt {
    let value = this.get("minChallengeRatio");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set minChallengeRatio(value: BigInt) {
    this.set("minChallengeRatio", Value.fromBigInt(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get blockTimestamp(): BigInt {
    let value = this.get("blockTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockTimestamp(value: BigInt) {
    this.set("blockTimestamp", Value.fromBigInt(value));
  }

  get transactionHash(): Bytes {
    let value = this.get("transactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set transactionHash(value: Bytes) {
    this.set("transactionHash", Value.fromBytes(value));
  }
}

export class OwnershipTransferred extends Entity {
  constructor(id: Bytes) {
    super();
    this.set("id", Value.fromBytes(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save OwnershipTransferred entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.BYTES,
        `Entities of type OwnershipTransferred must have an ID of type Bytes but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("OwnershipTransferred", id.toBytes().toHexString(), this);
    }
  }

  static loadInBlock(id: Bytes): OwnershipTransferred | null {
    return changetype<OwnershipTransferred | null>(
      store.get_in_block("OwnershipTransferred", id.toHexString())
    );
  }

  static load(id: Bytes): OwnershipTransferred | null {
    return changetype<OwnershipTransferred | null>(
      store.get("OwnershipTransferred", id.toHexString())
    );
  }

  get id(): Bytes {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set id(value: Bytes) {
    this.set("id", Value.fromBytes(value));
  }

  get previousOwner(): Bytes {
    let value = this.get("previousOwner");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set previousOwner(value: Bytes) {
    this.set("previousOwner", Value.fromBytes(value));
  }

  get newOwner(): Bytes {
    let value = this.get("newOwner");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set newOwner(value: Bytes) {
    this.set("newOwner", Value.fromBytes(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get blockTimestamp(): BigInt {
    let value = this.get("blockTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockTimestamp(value: BigInt) {
    this.set("blockTimestamp", Value.fromBigInt(value));
  }

  get transactionHash(): Bytes {
    let value = this.get("transactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set transactionHash(value: Bytes) {
    this.set("transactionHash", Value.fromBytes(value));
  }
}

export class ProtocolFeeUpdated extends Entity {
  constructor(id: Bytes) {
    super();
    this.set("id", Value.fromBytes(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save ProtocolFeeUpdated entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.BYTES,
        `Entities of type ProtocolFeeUpdated must have an ID of type Bytes but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("ProtocolFeeUpdated", id.toBytes().toHexString(), this);
    }
  }

  static loadInBlock(id: Bytes): ProtocolFeeUpdated | null {
    return changetype<ProtocolFeeUpdated | null>(
      store.get_in_block("ProtocolFeeUpdated", id.toHexString())
    );
  }

  static load(id: Bytes): ProtocolFeeUpdated | null {
    return changetype<ProtocolFeeUpdated | null>(
      store.get("ProtocolFeeUpdated", id.toHexString())
    );
  }

  get id(): Bytes {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set id(value: Bytes) {
    this.set("id", Value.fromBytes(value));
  }

  get protocolFee(): BigInt {
    let value = this.get("protocolFee");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set protocolFee(value: BigInt) {
    this.set("protocolFee", Value.fromBigInt(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get blockTimestamp(): BigInt {
    let value = this.get("blockTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockTimestamp(value: BigInt) {
    this.set("blockTimestamp", Value.fromBigInt(value));
  }

  get transactionHash(): Bytes {
    let value = this.get("transactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set transactionHash(value: Bytes) {
    this.set("transactionHash", Value.fromBytes(value));
  }
}

export class SubmitterFeeUpdated extends Entity {
  constructor(id: Bytes) {
    super();
    this.set("id", Value.fromBytes(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save SubmitterFeeUpdated entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.BYTES,
        `Entities of type SubmitterFeeUpdated must have an ID of type Bytes but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("SubmitterFeeUpdated", id.toBytes().toHexString(), this);
    }
  }

  static loadInBlock(id: Bytes): SubmitterFeeUpdated | null {
    return changetype<SubmitterFeeUpdated | null>(
      store.get_in_block("SubmitterFeeUpdated", id.toHexString())
    );
  }

  static load(id: Bytes): SubmitterFeeUpdated | null {
    return changetype<SubmitterFeeUpdated | null>(
      store.get("SubmitterFeeUpdated", id.toHexString())
    );
  }

  get id(): Bytes {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set id(value: Bytes) {
    this.set("id", Value.fromBytes(value));
  }

  get submitter(): Bytes {
    let value = this.get("submitter");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set submitter(value: Bytes) {
    this.set("submitter", Value.fromBytes(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get blockTimestamp(): BigInt {
    let value = this.get("blockTimestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockTimestamp(value: BigInt) {
    this.set("blockTimestamp", Value.fromBigInt(value));
  }

  get transactionHash(): Bytes {
    let value = this.get("transactionHash");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBytes();
    }
  }

  set transactionHash(value: Bytes) {
    this.set("transactionHash", Value.fromBytes(value));
  }
}

export class FactoryMangerLoader extends Entity {
  _entity: string;
  _field: string;
  _id: string;

  constructor(entity: string, id: string, field: string) {
    super();
    this._entity = entity;
    this._id = id;
    this._field = field;
  }

  load(): FactoryManger[] {
    let value = store.loadRelated(this._entity, this._id, this._field);
    return changetype<FactoryManger[]>(value);
  }
}

export class MDCLoader extends Entity {
  _entity: string;
  _field: string;
  _id: string;

  constructor(entity: string, id: string, field: string) {
    super();
    this._entity = entity;
    this._id = id;
    this._field = field;
  }

  load(): MDC[] {
    let value = store.loadRelated(this._entity, this._id, this._field);
    return changetype<MDC[]>(value);
  }
}

export class EBCManagerLoader extends Entity {
  _entity: string;
  _field: string;
  _id: string;

  constructor(entity: string, id: string, field: string) {
    super();
    this._entity = entity;
    this._id = id;
    this._field = field;
  }

  load(): EBCManager[] {
    let value = store.loadRelated(this._entity, this._id, this._field);
    return changetype<EBCManager[]>(value);
  }
}

export class MDCBindEBCLoader extends Entity {
  _entity: string;
  _field: string;
  _id: string;

  constructor(entity: string, id: string, field: string) {
    super();
    this._entity = entity;
    this._id = id;
    this._field = field;
  }

  load(): MDCBindEBC[] {
    let value = store.loadRelated(this._entity, this._id, this._field);
    return changetype<MDCBindEBC[]>(value);
  }
}
