// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class DealerUpdated extends ethereum.Event {
  get params(): DealerUpdated__Params {
    return new DealerUpdated__Params(this);
  }
}

export class DealerUpdated__Params {
  _event: DealerUpdated;

  constructor(event: DealerUpdated) {
    this._event = event;
  }

  get dealer(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get feeRatio(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get extraInfo(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
}

export class ETHDeposit extends ethereum.Event {
  get params(): ETHDeposit__Params {
    return new ETHDeposit__Params(this);
  }
}

export class ETHDeposit__Params {
  _event: ETHDeposit;

  constructor(event: ETHDeposit) {
    this._event = event;
  }

  get sender(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get amount(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }
}

export class OwnershipTransferred extends ethereum.Event {
  get params(): OwnershipTransferred__Params {
    return new OwnershipTransferred__Params(this);
  }
}

export class OwnershipTransferred__Params {
  _event: OwnershipTransferred;

  constructor(event: OwnershipTransferred) {
    this._event = event;
  }

  get previousOwner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newOwner(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class SubmissionUpdated extends ethereum.Event {
  get params(): SubmissionUpdated__Params {
    return new SubmissionUpdated__Params(this);
  }
}

export class SubmissionUpdated__Params {
  _event: SubmissionUpdated;

  constructor(event: SubmissionUpdated) {
    this._event = event;
  }

  get stratBlock(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }

  get endBlock(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get submitTimestamp(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }

  get profitRoot(): Bytes {
    return this._event.parameters[3].value.toBytes();
  }

  get stateTransTreeRoot(): Bytes {
    return this._event.parameters[4].value.toBytes();
  }
}

export class SubmitterRegistered extends ethereum.Event {
  get params(): SubmitterRegistered__Params {
    return new SubmitterRegistered__Params(this);
  }
}

export class SubmitterRegistered__Params {
  _event: SubmitterRegistered;

  constructor(event: SubmitterRegistered) {
    this._event = event;
  }

  get submiter(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get marginAmount(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }
}

export class Withdraw extends ethereum.Event {
  get params(): Withdraw__Params {
    return new Withdraw__Params(this);
  }
}

export class Withdraw__Params {
  _event: Withdraw;

  constructor(event: Withdraw) {
    this._event = event;
  }

  get user(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get chainId(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get token(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get debt(): BigInt {
    return this._event.parameters[3].value.toBigInt();
  }

  get amount(): BigInt {
    return this._event.parameters[4].value.toBigInt();
  }
}

export class FeeManager__getCurrentBlockInfoResultValue0Struct extends ethereum.Tuple {
  get stratBlock(): BigInt {
    return this[0].toBigInt();
  }

  get endBlock(): BigInt {
    return this[1].toBigInt();
  }

  get submitTimestamp(): BigInt {
    return this[2].toBigInt();
  }

  get profitRoot(): Bytes {
    return this[3].toBytes();
  }

  get stateTransTreeRoot(): Bytes {
    return this[4].toBytes();
  }
}

export class FeeManager__getDealerInfoResultValue0Struct extends ethereum.Tuple {
  get feeRatio(): BigInt {
    return this[0].toBigInt();
  }

  get extraInfoHash(): Bytes {
    return this[1].toBytes();
  }
}

export class FeeManager__submissionsResult {
  value0: BigInt;
  value1: BigInt;
  value2: BigInt;
  value3: Bytes;
  value4: Bytes;

  constructor(
    value0: BigInt,
    value1: BigInt,
    value2: BigInt,
    value3: Bytes,
    value4: Bytes
  ) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
    this.value4 = value4;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromUnsignedBigInt(this.value1));
    map.set("value2", ethereum.Value.fromUnsignedBigInt(this.value2));
    map.set("value3", ethereum.Value.fromFixedBytes(this.value3));
    map.set("value4", ethereum.Value.fromFixedBytes(this.value4));
    return map;
  }

  getStratBlock(): BigInt {
    return this.value0;
  }

  getEndBlock(): BigInt {
    return this.value1;
  }

  getSubmitTimestamp(): BigInt {
    return this.value2;
  }

  getProfitRoot(): Bytes {
    return this.value3;
  }

  getStateTransTreeRoot(): Bytes {
    return this.value4;
  }
}

export class FeeManager__withdrawLockCheckInputKeyStruct extends ethereum.Tuple {
  get chainId(): BigInt {
    return this[0].toBigInt();
  }

  get token(): Address {
    return this[1].toAddress();
  }

  get user(): Address {
    return this[2].toAddress();
  }
}

export class FeeManager extends ethereum.SmartContract {
  static bind(address: Address): FeeManager {
    return new FeeManager("FeeManager", address);
  }

  challengeStatus(): i32 {
    let result = super.call("challengeStatus", "challengeStatus():(uint8)", []);

    return result[0].toI32();
  }

  try_challengeStatus(): ethereum.CallResult<i32> {
    let result = super.tryCall(
      "challengeStatus",
      "challengeStatus():(uint8)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toI32());
  }

  durationCheck(): i32 {
    let result = super.call("durationCheck", "durationCheck():(uint8)", []);

    return result[0].toI32();
  }

  try_durationCheck(): ethereum.CallResult<i32> {
    let result = super.tryCall("durationCheck", "durationCheck():(uint8)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toI32());
  }

  getCurrentBlockInfo(): FeeManager__getCurrentBlockInfoResultValue0Struct {
    let result = super.call(
      "getCurrentBlockInfo",
      "getCurrentBlockInfo():((uint64,uint64,uint64,bytes32,bytes32))",
      []
    );

    return changetype<FeeManager__getCurrentBlockInfoResultValue0Struct>(
      result[0].toTuple()
    );
  }

  try_getCurrentBlockInfo(): ethereum.CallResult<
    FeeManager__getCurrentBlockInfoResultValue0Struct
  > {
    let result = super.tryCall(
      "getCurrentBlockInfo",
      "getCurrentBlockInfo():((uint64,uint64,uint64,bytes32,bytes32))",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      changetype<FeeManager__getCurrentBlockInfoResultValue0Struct>(
        value[0].toTuple()
      )
    );
  }

  getDealerInfo(dealer: Address): FeeManager__getDealerInfoResultValue0Struct {
    let result = super.call(
      "getDealerInfo",
      "getDealerInfo(address):((uint256,bytes32))",
      [ethereum.Value.fromAddress(dealer)]
    );

    return changetype<FeeManager__getDealerInfoResultValue0Struct>(
      result[0].toTuple()
    );
  }

  try_getDealerInfo(
    dealer: Address
  ): ethereum.CallResult<FeeManager__getDealerInfoResultValue0Struct> {
    let result = super.tryCall(
      "getDealerInfo",
      "getDealerInfo(address):((uint256,bytes32))",
      [ethereum.Value.fromAddress(dealer)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      changetype<FeeManager__getDealerInfoResultValue0Struct>(
        value[0].toTuple()
      )
    );
  }

  owner(): Address {
    let result = super.call("owner", "owner():(address)", []);

    return result[0].toAddress();
  }

  try_owner(): ethereum.CallResult<Address> {
    let result = super.tryCall("owner", "owner():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  submissions(): FeeManager__submissionsResult {
    let result = super.call(
      "submissions",
      "submissions():(uint64,uint64,uint64,bytes32,bytes32)",
      []
    );

    return new FeeManager__submissionsResult(
      result[0].toBigInt(),
      result[1].toBigInt(),
      result[2].toBigInt(),
      result[3].toBytes(),
      result[4].toBytes()
    );
  }

  try_submissions(): ethereum.CallResult<FeeManager__submissionsResult> {
    let result = super.tryCall(
      "submissions",
      "submissions():(uint64,uint64,uint64,bytes32,bytes32)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new FeeManager__submissionsResult(
        value[0].toBigInt(),
        value[1].toBigInt(),
        value[2].toBigInt(),
        value[3].toBytes(),
        value[4].toBytes()
      )
    );
  }

  submitter(param0: Address): BigInt {
    let result = super.call("submitter", "submitter(address):(uint256)", [
      ethereum.Value.fromAddress(param0)
    ]);

    return result[0].toBigInt();
  }

  try_submitter(param0: Address): ethereum.CallResult<BigInt> {
    let result = super.tryCall("submitter", "submitter(address):(uint256)", [
      ethereum.Value.fromAddress(param0)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  withdrawLock(param0: Bytes): boolean {
    let result = super.call("withdrawLock", "withdrawLock(bytes32):(bool)", [
      ethereum.Value.fromFixedBytes(param0)
    ]);

    return result[0].toBoolean();
  }

  try_withdrawLock(param0: Bytes): ethereum.CallResult<boolean> {
    let result = super.tryCall("withdrawLock", "withdrawLock(bytes32):(bool)", [
      ethereum.Value.fromFixedBytes(param0)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  withdrawLockCheck(key: FeeManager__withdrawLockCheckInputKeyStruct): boolean {
    let result = super.call(
      "withdrawLockCheck",
      "withdrawLockCheck((uint64,address,address)):(bool)",
      [ethereum.Value.fromTuple(key)]
    );

    return result[0].toBoolean();
  }

  try_withdrawLockCheck(
    key: FeeManager__withdrawLockCheckInputKeyStruct
  ): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "withdrawLockCheck",
      "withdrawLockCheck((uint64,address,address)):(bool)",
      [ethereum.Value.fromTuple(key)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }

  get owner_(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get manager_(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get _verifier(): Address {
    return this._call.inputValues[2].value.toAddress();
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class RegisterSubmitterCall extends ethereum.Call {
  get inputs(): RegisterSubmitterCall__Inputs {
    return new RegisterSubmitterCall__Inputs(this);
  }

  get outputs(): RegisterSubmitterCall__Outputs {
    return new RegisterSubmitterCall__Outputs(this);
  }
}

export class RegisterSubmitterCall__Inputs {
  _call: RegisterSubmitterCall;

  constructor(call: RegisterSubmitterCall) {
    this._call = call;
  }

  get marginAmount(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }

  get _submitter(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class RegisterSubmitterCall__Outputs {
  _call: RegisterSubmitterCall;

  constructor(call: RegisterSubmitterCall) {
    this._call = call;
  }
}

export class RenounceOwnershipCall extends ethereum.Call {
  get inputs(): RenounceOwnershipCall__Inputs {
    return new RenounceOwnershipCall__Inputs(this);
  }

  get outputs(): RenounceOwnershipCall__Outputs {
    return new RenounceOwnershipCall__Outputs(this);
  }
}

export class RenounceOwnershipCall__Inputs {
  _call: RenounceOwnershipCall;

  constructor(call: RenounceOwnershipCall) {
    this._call = call;
  }
}

export class RenounceOwnershipCall__Outputs {
  _call: RenounceOwnershipCall;

  constructor(call: RenounceOwnershipCall) {
    this._call = call;
  }
}

export class ResponsePositioningCall extends ethereum.Call {
  get inputs(): ResponsePositioningCall__Inputs {
    return new ResponsePositioningCall__Inputs(this);
  }

  get outputs(): ResponsePositioningCall__Outputs {
    return new ResponsePositioningCall__Outputs(this);
  }
}

export class ResponsePositioningCall__Inputs {
  _call: ResponsePositioningCall;

  constructor(call: ResponsePositioningCall) {
    this._call = call;
  }

  get response(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }
}

export class ResponsePositioningCall__Outputs {
  _call: ResponsePositioningCall;

  constructor(call: ResponsePositioningCall) {
    this._call = call;
  }
}

export class StartChallengeCall extends ethereum.Call {
  get inputs(): StartChallengeCall__Inputs {
    return new StartChallengeCall__Inputs(this);
  }

  get outputs(): StartChallengeCall__Outputs {
    return new StartChallengeCall__Outputs(this);
  }
}

export class StartChallengeCall__Inputs {
  _call: StartChallengeCall;

  constructor(call: StartChallengeCall) {
    this._call = call;
  }

  get marginAmount(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }

  get _submitter(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class StartChallengeCall__Outputs {
  _call: StartChallengeCall;

  constructor(call: StartChallengeCall) {
    this._call = call;
  }
}

export class SubmitCall extends ethereum.Call {
  get inputs(): SubmitCall__Inputs {
    return new SubmitCall__Inputs(this);
  }

  get outputs(): SubmitCall__Outputs {
    return new SubmitCall__Outputs(this);
  }
}

export class SubmitCall__Inputs {
  _call: SubmitCall;

  constructor(call: SubmitCall) {
    this._call = call;
  }

  get startBlock(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }

  get endBlock(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get profitRoot(): Bytes {
    return this._call.inputValues[2].value.toBytes();
  }

  get stateTransTreeRoot(): Bytes {
    return this._call.inputValues[3].value.toBytes();
  }
}

export class SubmitCall__Outputs {
  _call: SubmitCall;

  constructor(call: SubmitCall) {
    this._call = call;
  }
}

export class TransferOwnershipCall extends ethereum.Call {
  get inputs(): TransferOwnershipCall__Inputs {
    return new TransferOwnershipCall__Inputs(this);
  }

  get outputs(): TransferOwnershipCall__Outputs {
    return new TransferOwnershipCall__Outputs(this);
  }
}

export class TransferOwnershipCall__Inputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }

  get newOwner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class TransferOwnershipCall__Outputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }
}

export class UpdateDealerCall extends ethereum.Call {
  get inputs(): UpdateDealerCall__Inputs {
    return new UpdateDealerCall__Inputs(this);
  }

  get outputs(): UpdateDealerCall__Outputs {
    return new UpdateDealerCall__Outputs(this);
  }
}

export class UpdateDealerCall__Inputs {
  _call: UpdateDealerCall;

  constructor(call: UpdateDealerCall) {
    this._call = call;
  }

  get feeRatio(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }

  get extraInfo(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }
}

export class UpdateDealerCall__Outputs {
  _call: UpdateDealerCall;

  constructor(call: UpdateDealerCall) {
    this._call = call;
  }
}

export class WithdrawVerificationCall extends ethereum.Call {
  get inputs(): WithdrawVerificationCall__Inputs {
    return new WithdrawVerificationCall__Inputs(this);
  }

  get outputs(): WithdrawVerificationCall__Outputs {
    return new WithdrawVerificationCall__Outputs(this);
  }
}

export class WithdrawVerificationCall__Inputs {
  _call: WithdrawVerificationCall;

  constructor(call: WithdrawVerificationCall) {
    this._call = call;
  }

  get smtLeaves(): Array<WithdrawVerificationCallSmtLeavesStruct> {
    return this._call.inputValues[0].value.toTupleArray<
      WithdrawVerificationCallSmtLeavesStruct
    >();
  }

  get siblings(): Array<Array<WithdrawVerificationCallSiblingsStruct>> {
    return this._call.inputValues[1].value.toTupleMatrix<
      WithdrawVerificationCallSiblingsStruct
    >();
  }

  get startIndex(): Array<i32> {
    return this._call.inputValues[2].value.toI32Array();
  }

  get firstZeroBits(): Array<Bytes> {
    return this._call.inputValues[3].value.toBytesArray();
  }

  get bitmaps(): Array<BigInt> {
    return this._call.inputValues[4].value.toBigIntArray();
  }

  get withdrawAmount(): Array<BigInt> {
    return this._call.inputValues[5].value.toBigIntArray();
  }
}

export class WithdrawVerificationCall__Outputs {
  _call: WithdrawVerificationCall;

  constructor(call: WithdrawVerificationCall) {
    this._call = call;
  }
}

export class WithdrawVerificationCallSmtLeavesStruct extends ethereum.Tuple {
  get key(): WithdrawVerificationCallSmtLeavesKeyStruct {
    return changetype<WithdrawVerificationCallSmtLeavesKeyStruct>(
      this[0].toTuple()
    );
  }

  get value(): WithdrawVerificationCallSmtLeavesValueStruct {
    return changetype<WithdrawVerificationCallSmtLeavesValueStruct>(
      this[1].toTuple()
    );
  }
}

export class WithdrawVerificationCallSmtLeavesKeyStruct extends ethereum.Tuple {
  get chainId(): BigInt {
    return this[0].toBigInt();
  }

  get token(): Address {
    return this[1].toAddress();
  }

  get user(): Address {
    return this[2].toAddress();
  }
}

export class WithdrawVerificationCallSmtLeavesValueStruct extends ethereum.Tuple {
  get token(): Address {
    return this[0].toAddress();
  }

  get chainId(): BigInt {
    return this[1].toBigInt();
  }

  get amount(): BigInt {
    return this[2].toBigInt();
  }

  get debt(): BigInt {
    return this[3].toBigInt();
  }
}

export class WithdrawVerificationCallSiblingsStruct extends ethereum.Tuple {
  get mergeType(): i32 {
    return this[0].toI32();
  }

  get mergeValue(): WithdrawVerificationCallSiblingsMergeValueStruct {
    return changetype<WithdrawVerificationCallSiblingsMergeValueStruct>(
      this[1].toTuple()
    );
  }
}

export class WithdrawVerificationCallSiblingsMergeValueStruct extends ethereum.Tuple {
  get value1(): i32 {
    return this[0].toI32();
  }

  get value2(): Bytes {
    return this[1].toBytes();
  }

  get value3(): Bytes {
    return this[2].toBytes();
  }
}
